<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Blender Render Launcher</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Scripts\*.py" CopyToOutputDirectory="PreserveNewest" />
    <None Remove="Assets\blender-render-icon.png" />
    <Resource Include="Assets\blender-render-icon.png" />
  </ItemGroup>
</Project>
