<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Blender Render Launcher</AssemblyName>
    <Version>5.4.0</Version>
    <FileVersion>5.4.0.0</FileVersion>
    <AssemblyVersion>5.4.0.0</AssemblyVersion>
    <ApplicationIcon>Assets\blender-render-icon.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scripts\*.py" LogicalName="BlenderRenderHeadless.Scripts.%(Filename)%(Extension)" />
    <None Remove="Assets\blender-render-icon.png" />
    <Resource Include="Assets\blender-render-icon.png" />
    <None Include="Assets\blender-render-icon.ico" />
  </ItemGroup>
</Project>
